export const user = [
  {
    id: 1,
    name: "Ashu Priya",
    email: "ashu@gmail.com",
    image1: "/Image/Profile/ashu.png",
    image2: "/Image/Profile/ashumin.png",
    gender: "",
    age: "",
    info: "sjkja sajdhsd ndhsss djjssssss ajjjjjjja ajshhasaj jdshd",
    phone_number: "",
    alt_phone_naumber: "",
    social_url: "",
    blood_group: "",
    weight: "",
    address: {
      street_address: "",
      city: "",
      post_code: "",
    },
    donation: {
      level: "Top Rated Donor",
      donation_info: [
        {
          date: new Date(),
          hospital_name: "Saint sebastain Hospital",
          quantity: 1,
        },
        {
          date: new Date(),
          hospital_name: "Saint sebastain Hospital",
          quantity: 1,
        },
        {
          date: new Date(),
          hospital_name: "Saint sebastain Hospital",
          quantity: 1,
        },
      ],
    },

    request_info: [
      {
        id: 1,
        city: "",
        blood_group: "O+",
        req_type: "",
        relation: "",
        date: new Date(),
        hospital_name: "Jarin Hospital",
        manage: false,
      },
      {
        id: 2,
        city: "",
        blood_group: "O+",
        req_type: "",
        relation: "",
        date: new Date(),
        hospital_name: "Jarin Hospital",
        manage: false,
      },
      {
        id: 3,
        city: "",
        blood_group: "+",
        req_type: "my_req",
        relation: "",
        date: new Date(),
        hospital_name: "Jarin Hospital",
        manage: false,
      },
      {
        id: 4,
        city: "",
        blood_group: "O+",
        req_type: "my_req",
        relation: "",
        date: new Date(),
        hospital_name: "Jarin Hospital",
        manage: true,
      },
      {
        id: 5,
        city: "",
        blood_group: "O+",
        req_type: "urgent_req",
        relation: "",
        date: new Date(),
        hospital_name: "Jarin Hospital",
        manage: false,
      },
      {
        id: 6,
        city: "",
        blood_group: "O+",
        req_type: "urgent_req",
        relation: "",
        date: new Date(),
        hospital_name: "Jarin Hospital",
        manage: false,
      },
      {
        id: 7,
        city: "",
        blood_group: "O+",
        req_type: "scheduled",
        relation: "",
        date: new Date(),
        hospital_name: "Jarin Hospital",
        manage: false,
      },
    ],
  },
  {
    id: 2,
    name: "John Doe",
    email: "hohn@gmail.com",
    image1: "/Image/Profile/doe.png",
    image2: "/Image/Profile/doemin.png",
    gender: "",
    age: "",
    info: "sjkja sajdhsd ndhsss djjssssss ajjjjjjja ajshhasaj jdshd",
    phone_number: "",
    alt_phone_naumber: "",
    social_url: "",
    blood_group: "",
    weight: "",
    address: {
      street_address: "",
      city: "",
      post_code: "",
    },
    donation: {
      level: "Top Rated Donor",
      donation_info: [
        {
          date: new Date(),
          hospital_name: "Saint sebastain Hospital",
          quantity: 1,
        },
        {
          date: new Date(),
          hospital_name: "Saint sebastain Hospital",
          quantity: 1,
        },
        {
          date: new Date(),
          hospital_name: "Saint sebastain Hospital",
          quantity: 1,
        },
      ],
    },

    request_info: [
      {
        id: 1,
        city: "",
        blood_group: "O+",
        req_type: "urgent_req",
        relation: "",
        date: new Date(),
        hospital_name: "Jarin Hospital",
        manage: false,
      },
      {
        id: 2,
        city: "",
        blood_group: "O+",
        req_type: "urgent_req",
        relation: "",
        date: new Date(),
        hospital_name: "Jarin Hospital",
        manage: false,
      },
      {
        id: 3,
        city: "",
        blood_group: "+",
        req_type: "my_req",
        relation: "",
        date: new Date(),
        hospital_name: "Jarin Hospital",
        manage: false,
      },
      {
        id: 4,
        city: "",
        blood_group: "O+",
        req_type: "my_req",
        relation: "",
        date: new Date(),
        hospital_name: "Jarin Hospital",
        manage: false,
      },
      {
        id: 5,
        city: "",
        blood_group: "O+",
        req_type: "",
        relation: "",
        date: new Date(),
        hospital_name: "Jarin Hospital",
        manage: false,
      },
      {
        id: 6,
        city: "",
        blood_group: "O+",
        req_type: "recent_req",
        relation: "",
        date: new Date(),
        hospital_name: "Jarin Hospital",
        manage: false,
      },
      {
        id: 7,
        city: "",
        blood_group: "O+",
        req_type: "recent_req",
        relation: "",
        date: new Date(),
        hospital_name: "Jarin Hospital",
        manage: false,
      },
    ],
  },
];
